language: python
python:
  - "3.6"

os:
  - linux

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install coveralls codecov

script:
  - cd pruebas
  - nosetests --with-coverage --cover-package=tinamit
  - coveralls --exclude-lines-pattern "*/trads*"
  - codecov