language: python
python:
  - "3.6"
  - "3.7"

os:
  - linux
  - osx

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install coveralls coverage

script:
  - cd pruebas
  - nosetests --with-coverage --cover-package=tinamit
  - coveralls
  - codecov